language: csharp
dist: trusty
solution: PatientManagement.sln
mono: none
sudo: false
dotnet: 2.0.0
before_install:
- dotnet add PatientManagement/PatientManagement.Web/PatientManagement.Web.csproj package signalr -s https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
script:
- dotnet build PatientManagement.Public/PatientManagement.Public.csproj
- dotnet build PatientManagement/PatientManagement.Web/PatientManagement.Web.csproj 

- mkdir -p publish_clario_admin_release
- dotnet publish PatientManagement/PatientManagement.Web/*.csproj -c Release -f netcoreapp2.0 -o ../../publish_clario_admin_release

- docker build -t clario_admin -f PatientManagement/PatientManagement.Web/Dockerfile .

- echo "TRAVIS_EVENT_TYPE is $TRAVIS_EVENT_TYPE"
- echo "TRAVIS_BRANCH is $TRAVIS_BRANCH"
- echo "TRAVIS_BUILD_NUMBER is $TRAVIS_BUILD_NUMBER"

- docker login -u $TD_DOCKER_USERNAME -p $TD_DOCKER_PASSWORD
- docker tag clario_admin s2kdesign/clario_admin:$TRAVIS_BUILD_NUMBER-release
- docker push s2kdesign/clario_admin:$TRAVIS_BUILD_NUMBER-release
