language: csharp
dist: trusty
solution: PatientManagement.sln
mono: latest
sudo: false
dotnet: 2.0.0
before_install:
- dotnet add PatientManagement/PatientManagement.Web/PatientManagement.Web.csproj package signalr -s https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
script:
- dotnet build PatientManagement.Public/PatientManagement.Public.csproj
- dotnet build PatientManagement/PatientManagement.Web/PatientManagement.Web.csproj 
