version: '3.4'

services:
  patientmanagement.web:
    image: clario_admin
    build:
      context: ./PatientManagement/PatientManagement.Web
      dockerfile: Dockerfile
    depends_on: 
        - sql.data

  sql.data:
    image: microsoft/mssql-server-linux
